server.port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgres
    password: lockheed
    driver-class-name: org.postgresql.Driver
  jpa.hibernate.ddl-auto: create
  cors.front-origin: http://localhost:4200

security.jwt.token.secret-key: another-secret

